name: Linux Build

on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run publish
        env:
          CI: true

  build-win:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
      issues: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run publish
        env:
          CI: true

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      issues: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APPLE_BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Import Certificate
        env:
          MACOS_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        run: |
          echo $MACOS_CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run publish
        env:
          CI: true

